CREATE TABLE `companies` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) DEFAULT NULL,
	`ein` VARCHAR(255) DEFAULT NULL,
	`doing_business_as` VARCHAR(255) DEFAULT NULL,
	`type_of_business` VARCHAR(255) DEFAULT NULL,
	`phone` VARCHAR(255) DEFAULT NULL,
	`address` VARCHAR(255) DEFAULT NULL,
	`city` VARCHAR(255) DEFAULT NULL,
	`state` VARCHAR(255) DEFAULT NULL,
	`zip` VARCHAR(255) DEFAULT NULL,
	`mailing_address` VARCHAR(255) DEFAULT NULL,
	`mailing_address_2` VARCHAR(255) DEFAULT NULL,
	`mailing_city` VARCHAR(255) DEFAULT NULL,
	`mailing_state` VARCHAR(255) DEFAULT NULL,
	`mailing_zip` VARCHAR(255) DEFAULT NULL,
	`cik` VARCHAR(255) DEFAULT NULL,
	`end_of_fiscal_year` VARCHAR(255) DEFAULT NULL,
	`incorporation_state` VARCHAR(255) DEFAULT NULL,
	`incorporation_sub_division` VARCHAR(255) DEFAULT NULL,
	`incorporation_country` VARCHAR(255) DEFAULT NULL,
	`filing_year` VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB;
